#  Copyright (c) 2001 Dan Gudmundsson
#  See the file "license.terms" for information on usage and redistribution
#  of this file, and for a DISCLAIMER OF ALL WARRANTIES.
# 
#     $Id$
#
ESRC = .
EBIN = .
ERLC = erlc
ERLINC = ..\include
ERL_FLAGS = -I..\.. -I$(ERLINC)
ERL_COMPILE_FLAGS = -pa ..\..\esdl\ebin

!if !exist(..\ebin)
!	if [mkdir ..\ebin]
!	error "esdl: cannot create ..\priv"
!	endif
!endif

TestTargets		= \
		$(EBIN)\testsprite.beam \
		$(EBIN)\testgl.beam \
		$(EBIN)\testbin.beam \
		$(EBIN)\erldemo.beam \
		$(EBIN)\testaudio.beam \
		$(EBIN)\testjoy.beam 

REMOVE_FILES=$(TestTargets:.beam=.removed)

.SUFFIXES: .erl .beam .removed
# Targets
target: $(TestTargets)

clean:   $(REMOVE_FILES)

{$(EBIN)}.beam{$(EBIN)}.removed:
	-del $(*R).beam
# Rules
{.}.erl{$(EBIN)}.beam:
	$(ERLC) -W -bbeam $(ERL_FLAGS) $(ERL_COMPILE_FLAGS) -o$(EBIN) $(*B).erl
